

# 由于当前国内环境复杂, ipv6的国外网站基本没法用, 所以这里默认上来就禁用掉避免麻烦
disable_ipv6: true

# binary software version
docker_version: 18.09.9
kubernetes_version: v1.16.3
kubernetes_cni_version: v0.8.6
cfssl_version: 1.4.1
etcd_version: v3.4.9
gluster_version: 4.1.9

# ------------ addons ------------------------------
# network plugin(options: flannel, kube-ovn)
addons_network: flannel
flannel_version: v0.12.0
kube-ovn_version: v1.4.0

# kubernete configuration
# eg. token: b0f7b8.8d1767879297d85c
token: ffffff.ffffffffffffffff
service_cidr: "172.28.0.0/16"
pod_network_cidr: "172.29.0.0/16"
cluster_domain: "cluster.me"
network_interface: "eth0"

ansible_ssh_user: root
ansible_ssh_pass: Changeme_123
ansible_connection: ssh

