
# binary software version
docker_version: 18.09.9
kubernetes_version: v1.16.3
kubernetes_cni_version: v0.8.6
cfssl_version: 1.4.1
etcd_version: v3.4.9
gluster_version: 4.1.9

# docker software version
flannel_version: v0.11.0

# kubernete configuration
# eg. token: b0f7b8.8d1767879297d85c
token: ffffff.ffffffffffffffff
service_cidr: "220.0.0.0/12"
pod_network_cidr: "219.0.0.0/8"
cluster_domain: "cluster.me"
network_interface: "eth0"

ansible_ssh_user: root
ansible_ssh_pass: Changeme_123
ansible_connection: ssh
