---
- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - { role: basic, tags: basic }
    - { role: docker, tags: docker }

- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: etcd, tags: etcd }
    - { role: kubernetes/server, tags: k8s-master }
