---
- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - { role: hack, tags: hack }
    - { role: basic, tags: basic }
    - { role: docker, tags: docker }

- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: etcd, tags: etcd }
    - { role: kubernetes/server, tags: master }

- hosts: node
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/node, tags: node }
