---
- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: kubeadm reset
      shell: |
        kubeadm reset --force;
      ignore_errors: True

    - name: remvoe interface
      shell: |
        kubeadm reset --force;
        ifconfig {{ item }} down;
        ip link delete {{ item }};
      ignore_errors: True
      with_items:
        - flannel.1
        - cni0
        - genev_sys_6081
        - mirror0
        - ovn0

- hosts: master
  gather_facts: no
  become: yes
  tasks:
    - name: clean etcd
      shell: |
        systemctl stop etcd
        rm -rf /etc/etcd
        rm -rf /var/lib/etcd
      ignore_errors: True
