---

# - name: check kubectl.conf exists
# - name: check if kubadm installed or not
#   stat:
#     path: "/etc/kubernetes/admin.conf"
#   register: var_kubeadm_conf

- name: kubeadm join ...
  include_tasks: kubeadm_join.yml