---
- name: ensures dirs
  file: path={{ item }} state=directory
  with_items:
    - /tmp/repository

- name: download all
  shell: |
    while echo '{{ item.sha256sum }} {{ item.dest }}' | sha256sum --check --status &>/dev/null; [ $? -ne 0 ]; do 
        curl -sSLf {{ binaries_mirror }}/{{ item.sha256sum }} -o {{ item.dest }} || curl -sSLf {{ item.url }} -o {{ item.dest }}; 
    done
  with_items:
    - {
        dest: "/tmp/repository/{{ binaries['docker']['name'] }}",
        sha256sum: "{{ binaries['docker']['versions'][docker_version]['sha256sum'] }}",
        url: "{{ binaries['docker']['versions'][docker_version]['url'] }}",
      }
    - {
        dest: "/tmp/repository/{{ binaries['cfssl']['name'] }}",
        sha256sum: "{{ binaries['cfssl']['versions'][cfssl_version]['sha256sum'] }}",
        url: "{{ binaries['cfssl']['versions'][cfssl_version]['url'] }}",
      }
    - {
        dest: "/tmp/repository/{{ binaries['cfssljson']['name'] }}",
        sha256sum: "{{ binaries['cfssljson']['versions'][cfssl_version]['sha256sum'] }}",
        url: "{{ binaries['cfssljson']['versions'][cfssl_version]['url'] }}",
      }
    - {
        dest: "/tmp/repository/{{ binaries['etcd']['name'] }}",
        sha256sum: "{{ binaries['etcd']['versions'][etcd_version]['sha256sum'] }}",
        url: "{{ binaries['etcd']['versions'][etcd_version]['url'] }}",
      }
    - {
        dest: "/tmp/repository/{{ binaries['kubernetes-server']['name'] }}",
        sha256sum: "{{ binaries['kubernetes-server']['versions'][kubernetes_version]['sha256sum'] }}",
        url: "{{ binaries['kubernetes-server']['versions'][kubernetes_version]['url'] }}",
      }
    - {
        dest: "/tmp/repository/{{ binaries['kubernetes-node']['name'] }}",
        sha256sum: "{{ binaries['kubernetes-node']['versions'][kubernetes_version]['sha256sum'] }}",
        url: "{{ binaries['kubernetes-node']['versions'][kubernetes_version]['url'] }}",
      }
    - {
        dest: "/tmp/repository/{{ binaries['cni-plugins']['name'] }}",
        sha256sum: "{{ binaries['cni-plugins']['versions'][kubernetes_cni_version]['sha256sum'] }}",
        url: "{{ binaries['cni-plugins']['versions'][kubernetes_cni_version]['url'] }}",
      }
    - {
        dest: "/tmp/repository/{{ binaries['helm']['name'] }}",
        sha256sum: "{{ binaries['helm']['versions'][helm_version]['sha256sum'] }}",
        url: "{{ binaries['helm']['versions'][helm_version]['url'] }}",
      }
    - {
        dest: "/tmp/repository/{{ binaries['kubectl-ko']['name'] }}",
        sha256sum: "{{ binaries['kubectl-ko']['versions'][kube_ovn_version]['sha256sum'] }}",
        url: "{{ binaries['kubectl-ko']['versions'][kube_ovn_version]['url'] }}",
      }
