---

# kuberntes不允许主机名出现下划线
- name: change hostname
  shell: |
    hostnamectl set-hostname "{{ inventory_hostname | replace("_", "-") }}"

- name: turn off selinux
  selinux:
   state: disabled

- name: stop and disable firewalld
  service:
   name: firewalld
   state: stopped
   enabled: False

- name: install nessary dependencies
  include_tasks:  "yum-install.yml"
  when:
   - ansible_os_family == "RedHat"

- name: binary-download
  include_tasks:  "binary-download.yml"