---
- name: install packages
  yum:
    state: present
    # update_cache: yes
    name:
      - bind-utils
      - curl
      - net-tools
      - unzip
      - gzip
      - tar
      - tree
      - git
      - zsh
      - telnet
      - iptables
      - conntrack
      - sysstat
      - wget
      - lrzsz
      - iptables-services
      - ipvsadm
      - ipset
