inputs:
  ipType:
    default: 5_bgp
    description: >
      5_bgp：VPC动态BGP；5_sbgp：VPC静态BGP；5_telcom：中国电信；5_union：中国联通约束：只可以有如下取值:
      5_telcom | 5_union | 5_bgp |
      5_sbgp，各region取值范围为：东北-大连：5_telcom、5_union；华南-广州：5_bgp；华东-上海二：5_sbgp；华北-北京一：5_bgp、5_sbgp；亚太-香港：5_bgp；华北-北京四：5_bgp。
    type: HuaweiCloud.VPC.EIP.Spec.Name
  nodeAvailabilityZone:
    default: cn-east-2c
    description: 可用分区
    type: HuaweiCloud.ECS.AvailabilityZone.Name
  nodeFlavor:
    default: s3.small.1
    description: 节点规格
    type: HuaweiCloud.ECS.Flavor.Name
  nodeImage:
    default: 9526f9b7-423c-4fdc-92ad-f1630a524652
    description: 节点镜像(CentOS 7)
    type: HuaweiCloud.ECS.Image.Id
  sshKey:
    description: 创建节点登录使用的密钥对(需提前创建好)
    type: HuaweiCloud.ECS.KeyPair.Name
metadata:
  Designer:
    2617c555-7896-4b35-9427-bb10a72d7973:
      size:
        width: 780
        height: 330
      position:
        x: -110
        y: 210
      z: 1
      embeds:
        - 835f9bd4-ff5c-4aa7-bf86-d63fcf4430a0
        - e6a98745-6699-4590-81f1-70d2e124e5a0
        - 66bb7fed-c285-489f-bb02-088fbbff9cc2
        - c8272480-4c58-4e86-b66e-16e60511cc87
        - 2b148edd-fad5-4cef-82a3-4f1f3c2db9d1
        - 96c8c995-f44d-4018-88e2-f529bf70db51
        - fbd0f61a-666f-40bb-9c0f-e48f47ef23c6
    2b148edd-fad5-4cef-82a3-4f1f3c2db9d1:
      size:
        width: 60
        height: 60
      position:
        x: 20
        y: 410
      z: 2
      parent: 2617c555-7896-4b35-9427-bb10a72d7973
      isassociatedwith:
        - 835f9bd4-ff5c-4aa7-bf86-d63fcf4430a0
        - e6a98745-6699-4590-81f1-70d2e124e5a0
    66bb7fed-c285-489f-bb02-088fbbff9cc2:
      size:
        width: 60
        height: 60
      position:
        x: 140
        y: 250
      z: 2
      parent: 2617c555-7896-4b35-9427-bb10a72d7973
      isassociatedwith:
        - 835f9bd4-ff5c-4aa7-bf86-d63fcf4430a0
        - e6a98745-6699-4590-81f1-70d2e124e5a0
    835f9bd4-ff5c-4aa7-bf86-d63fcf4430a0:
      size:
        width: 60
        height: 60
      position:
        x: -90
        y: 240
      z: 2
      parent: 2617c555-7896-4b35-9427-bb10a72d7973
    899baeda-d630-48b6-935b-bdb0692ce659:
      size:
        width: 60
        height: 60
      position:
        x: 470
        y: 410
      z: 3
      parent: e6a98745-6699-4590-81f1-70d2e124e5a0
      embeds: ''
    96c8c995-f44d-4018-88e2-f529bf70db51:
      size:
        width: 60
        height: 60
      position:
        x: 20
        y: 250
      z: 2
      parent: 2617c555-7896-4b35-9427-bb10a72d7973
      isassociatedwith:
        - 835f9bd4-ff5c-4aa7-bf86-d63fcf4430a0
        - e6a98745-6699-4590-81f1-70d2e124e5a0
    c1d63aac-3db7-42f7-916b-ad9a8fe09273:
      size:
        width: 60
        height: 60
      position:
        x: 370
        y: 410
      z: 3
      parent: e6a98745-6699-4590-81f1-70d2e124e5a0
    c8272480-4c58-4e86-b66e-16e60511cc87:
      size:
        width: 60
        height: 60
      position:
        x: 380
        y: 250
      z: 2
      parent: 2617c555-7896-4b35-9427-bb10a72d7973
      isassociatedwith:
        - 835f9bd4-ff5c-4aa7-bf86-d63fcf4430a0
        - e6a98745-6699-4590-81f1-70d2e124e5a0
    e6a98745-6699-4590-81f1-70d2e124e5a0:
      size:
        width: 300
        height: 120
      position:
        x: 350
        y: 390
      z: 2
      parent: 2617c555-7896-4b35-9427-bb10a72d7973
      embeds:
        - c1d63aac-3db7-42f7-916b-ad9a8fe09273
        - 899baeda-d630-48b6-935b-bdb0692ce659
        - f0f88c9f-e6c9-4e2d-9fe8-a35193d6cfd3
    f0f88c9f-e6c9-4e2d-9fe8-a35193d6cfd3:
      size:
        width: 60
        height: 60
      position:
        x: 560
        y: 410
      z: 3
      parent: e6a98745-6699-4590-81f1-70d2e124e5a0
      embeds: ''
    fbd0f61a-666f-40bb-9c0f-e48f47ef23c6:
      size:
        width: 60
        height: 60
      position:
        x: 260
        y: 250
      z: 2
      parent: 2617c555-7896-4b35-9427-bb10a72d7973
      isassociatedwith:
        - 835f9bd4-ff5c-4aa7-bf86-d63fcf4430a0
        - e6a98745-6699-4590-81f1-70d2e124e5a0
    0d8c573f-e385-4056-96b6-6fcc39828c5a:
      source:
        id: 66bb7fed-c285-489f-bb02-088fbbff9cc2
      target:
        id: e6a98745-6699-4590-81f1-70d2e124e5a0
      z: 2
    adc8eab6-b6ce-462c-957d-02579139608c:
      source:
        id: 66bb7fed-c285-489f-bb02-088fbbff9cc2
      target:
        id: 835f9bd4-ff5c-4aa7-bf86-d63fcf4430a0
      z: 2
    11244d67-973c-4516-947c-b1d25b6d419b:
      source:
        id: c8272480-4c58-4e86-b66e-16e60511cc87
      target:
        id: e6a98745-6699-4590-81f1-70d2e124e5a0
      z: 2
    bbcbb8bf-fe6c-49a1-8317-e0dbf3454cc3:
      source:
        id: c8272480-4c58-4e86-b66e-16e60511cc87
      target:
        id: 835f9bd4-ff5c-4aa7-bf86-d63fcf4430a0
      z: 2
    c060037d-8a2f-41b4-97f1-5b9dee48751b:
      source:
        id: 2b148edd-fad5-4cef-82a3-4f1f3c2db9d1
      target:
        id: e6a98745-6699-4590-81f1-70d2e124e5a0
      z: 2
    9c22d4fd-7e4a-4513-8bee-4bab75658b40:
      source:
        id: 2b148edd-fad5-4cef-82a3-4f1f3c2db9d1
      target:
        id: 835f9bd4-ff5c-4aa7-bf86-d63fcf4430a0
      z: 2
    0eca1087-93e4-430f-bf42-26c3f30d2336:
      source:
        id: 96c8c995-f44d-4018-88e2-f529bf70db51
      target:
        id: e6a98745-6699-4590-81f1-70d2e124e5a0
      z: 2
    43ef812f-4617-451c-9e06-4bb3074fb239:
      source:
        id: 96c8c995-f44d-4018-88e2-f529bf70db51
      target:
        id: 835f9bd4-ff5c-4aa7-bf86-d63fcf4430a0
      z: 2
    13f2484f-0c25-4847-9e77-508456b381b7:
      source:
        id: fbd0f61a-666f-40bb-9c0f-e48f47ef23c6
      target:
        id: e6a98745-6699-4590-81f1-70d2e124e5a0
      z: 2
    6fc60884-97f8-47cc-bda0-ddc64c0975ee:
      source:
        id: fbd0f61a-666f-40bb-9c0f-e48f47ef23c6
      target:
        id: 835f9bd4-ff5c-4aa7-bf86-d63fcf4430a0
      z: 2
  relationships:
    2b148edd-fad5-4cef-82a3-4f1f3c2db9d1:
      references:
        nics.subnetId:
          - get_reference: vpc-subnet
        securityGroups.id:
          - get_reference: vpc-sg
        vpcId:
          get_reference: vpc-vpc
    66bb7fed-c285-489f-bb02-088fbbff9cc2:
      references:
        nics.subnetId:
          - get_reference: vpc-subnet
        securityGroups.id:
          - get_reference: vpc-sg
        vpcId:
          get_reference: vpc-vpc
    835f9bd4-ff5c-4aa7-bf86-d63fcf4430a0:
      references:
        vpcId:
          get_reference: vpc-vpc
    899baeda-d630-48b6-935b-bdb0692ce659:
      references:
        securityGroupId:
          get_reference: vpc-sg
    96c8c995-f44d-4018-88e2-f529bf70db51:
      references:
        nics.subnetId:
          - get_reference: vpc-subnet
        securityGroups.id:
          - get_reference: vpc-sg
        vpcId:
          get_reference: vpc-vpc
    c1d63aac-3db7-42f7-916b-ad9a8fe09273:
      references:
        securityGroupId:
          get_reference: vpc-sg
    c8272480-4c58-4e86-b66e-16e60511cc87:
      references:
        nics.subnetId:
          - get_reference: vpc-subnet
        securityGroups.id:
          - get_reference: vpc-sg
        vpcId:
          get_reference: vpc-vpc
    e6a98745-6699-4590-81f1-70d2e124e5a0:
      references:
        vpcId:
          get_reference: vpc-vpc
    f0f88c9f-e6c9-4e2d-9fe8-a35193d6cfd3:
      references:
        securityGroupId:
          get_reference: vpc-sg
    fbd0f61a-666f-40bb-9c0f-e48f47ef23c6:
      references:
        nics.subnetId:
          - get_reference: vpc-subnet
        securityGroups.id:
          - get_reference: vpc-sg
        vpcId:
          get_reference: vpc-vpc
node_templates:
  ecs-gateway:
    metadata:
      Designer:
        id: fbd0f61a-666f-40bb-9c0f-e48f47ef23c6
    properties:
      availabilityZone:
        get_input: nodeAvailabilityZone
      flavor:
        get_input: nodeFlavor
      imageId:
        get_input: nodeImage
      instances: 1
      name:
        concat:
          - {get_input: HuaweiCloud.StackName}
          - '-'
          - gateway
      nics:
        - allowedAddressPairs:
            - ipAddress: ''
          ipAddress: 192.168.1.4
          ipCheck: false
          portSecurityEnabled: true
          subnetId:
            get_reference: vpc-subnet
      publicIP:
        eip:
          bandwidth:
            chargeMode: traffic
            shareType: PER
            size: 1
          ipType:
            get_input: ipType
      rootVolume:
        size: 50
        volumeType: SATA
      securityGroups:
        - id:
            get_reference: vpc-sg
      sshKeyName:
        get_input: sshKey
      vpcId:
        get_reference: vpc-vpc
    requirements:
      - vpcId:
          node: vpc-vpc
      - nics.subnetId:
          node: vpc-subnet
      - securityGroups.id:
          node: vpc-sg
    type: HuaweiCloud.ECS.CloudServer
  ecs-master:
    metadata:
      Designer:
        id: 96c8c995-f44d-4018-88e2-f529bf70db51
    properties:
      availabilityZone:
        get_input: nodeAvailabilityZone
      dataVolumes:
        - size: 40
          volumeType: SATA
      flavor:
        get_input: nodeFlavor
      imageId:
        get_input: nodeImage
      instances: 1
      name:
        concat:
          - {get_input: HuaweiCloud.StackName}
          - '-'
          - master
      nics:
        - allowedAddressPairs:
            - ipAddress: ''
          ipAddress: 192.168.1.2
          ipCheck: false
          portSecurityEnabled: true
          subnetId:
            get_reference: vpc-subnet
      publicIP:
        eip:
          bandwidth:
            chargeMode: traffic
            shareType: PER
            size: 1
          ipType:
            get_input: ipType
      rootVolume:
        size: 50
        volumeType: SATA
      securityGroups:
        - id:
            get_reference: vpc-sg
      sshKeyName:
        get_input: sshKey
      vpcId:
        get_reference: vpc-vpc
    requirements:
      - vpcId:
          node: vpc-vpc
      - nics.subnetId:
          node: vpc-subnet
      - securityGroups.id:
          node: vpc-sg
    type: HuaweiCloud.ECS.CloudServer
  ecs-node:
    metadata:
      Designer:
        id: 2b148edd-fad5-4cef-82a3-4f1f3c2db9d1
    properties:
      availabilityZone:
        get_input: nodeAvailabilityZone
      dataVolumes:
        - size: 100
          volumeType: SATA
      flavor:
        get_input: nodeFlavor
      imageId:
        get_input: nodeImage
      instances: 1
      name:
        concat:
          - {get_input: HuaweiCloud.StackName}
          - '-'
          - node
      nics:
        - allowedAddressPairs:
            - ipAddress: ''
          ipAddress: 192.168.1.6
          ipCheck: true
          portSecurityEnabled: true
          subnetId:
            get_reference: vpc-subnet
      publicIP:
        eip:
          bandwidth:
            chargeMode: traffic
            shareType: PER
            size: 1
          ipType:
            get_input: ipType
      rootVolume:
        size: 50
        volumeType: SATA
      securityGroups:
        - id:
            get_reference: vpc-sg
      sshKeyName:
        get_input: sshKey
      vpcId:
        get_reference: vpc-vpc
    requirements:
      - vpcId:
          node: vpc-vpc
      - nics.subnetId:
          node: vpc-subnet
      - securityGroups.id:
          node: vpc-sg
    type: HuaweiCloud.ECS.CloudServer
  ecs-snat:
    metadata:
      Designer:
        id: c8272480-4c58-4e86-b66e-16e60511cc87
    properties:
      availabilityZone:
        get_input: nodeAvailabilityZone
      flavor:
        get_input: nodeFlavor
      imageId:
        get_input: nodeImage
      instances: 1
      name:
        concat:
          - {get_input: HuaweiCloud.StackName}
          - '-'
          - snat
      nics:
        - allowedAddressPairs:
            - ipAddress: ''
          ipAddress: 192.168.1.5
          ipCheck: false
          portSecurityEnabled: true
          subnetId:
            get_reference: vpc-subnet
      publicIP:
        eip:
          bandwidth:
            chargeMode: traffic
            shareType: PER
            size: 1
          ipType:
            get_input: ipType
      rootVolume:
        size: 50
        volumeType: SATA
      securityGroups:
        - id:
            get_reference: vpc-sg
      sshKeyName:
        get_input: sshKey
      vpcId:
        get_reference: vpc-vpc
    requirements:
      - vpcId:
          node: vpc-vpc
      - nics.subnetId:
          node: vpc-subnet
      - securityGroups.id:
          node: vpc-sg
    type: HuaweiCloud.ECS.CloudServer
  ecs-storage:
    metadata:
      Designer:
        id: 66bb7fed-c285-489f-bb02-088fbbff9cc2
    properties:
      availabilityZone:
        get_input: nodeAvailabilityZone
      dataVolumes:
        - size: 30
          volumeType: SATA
      flavor:
        get_input: nodeFlavor
      imageId:
        get_input: nodeImage
      instances: 1
      name:
        concat:
          - {get_input: HuaweiCloud.StackName}
          - '-'
          - storage
      nics:
        - allowedAddressPairs:
            - ipAddress: ''
          ipAddress: 192.168.1.3
          ipCheck: false
          portSecurityEnabled: true
          subnetId:
            get_reference: vpc-subnet
      publicIP:
        eip:
          bandwidth:
            chargeMode: traffic
            shareType: PER
            size: 1
          ipType:
            get_input: ipType
      rootVolume:
        size: 50
        volumeType: SATA
      securityGroups:
        - id:
            get_reference: vpc-sg
      sshKeyName:
        get_input: sshKey
      vpcId:
        get_reference: vpc-vpc
    requirements:
      - vpcId:
          node: vpc-vpc
      - nics.subnetId:
          node: vpc-subnet
      - securityGroups.id:
          node: vpc-sg
    type: HuaweiCloud.ECS.CloudServer
  vpc-sg:
    metadata:
      Designer:
        id: e6a98745-6699-4590-81f1-70d2e124e5a0
    properties: {}
    requirements:
      - vpcId:
          node: vpc-vpc
    type: HuaweiCloud.VPC.SecurityGroup
  vpc-sg-rule-ingress-icmp:
    metadata:
      Designer:
        id: f0f88c9f-e6c9-4e2d-9fe8-a35193d6cfd3
    properties:
      direction: ingress
      ethertype: IPv4
      protocol: ICMP
      securityGroupId:
        get_reference: vpc-sg
    requirements:
      - securityGroupId:
          node: vpc-sg
    type: HuaweiCloud.VPC.SecurityGroupRule
  vpc-sg-rule-ingress-udp:
    metadata:
      Designer:
        id: 899baeda-d630-48b6-935b-bdb0692ce659
    properties:
      direction: ingress
      ethertype: IPv4
      maxPort: 65535
      minPort: 1
      protocol: UDP
      securityGroupId:
        get_reference: vpc-sg
    requirements:
      - securityGroupId:
          node: vpc-sg
    type: HuaweiCloud.VPC.SecurityGroupRule
  vpc-sg-rule-ingress-tcp:
    metadata:
      Designer:
        id: c1d63aac-3db7-42f7-916b-ad9a8fe09273
    properties:
      direction: ingress
      ethertype: IPv4
      maxPort: 65535
      minPort: 1
      protocol: TCP
      securityGroupId:
        get_reference: vpc-sg
    requirements:
      - securityGroupId:
          node: vpc-sg
    type: HuaweiCloud.VPC.SecurityGroupRule
  vpc-subnet:
    metadata:
      Designer:
        id: 835f9bd4-ff5c-4aa7-bf86-d63fcf4430a0
    properties:
      cidr: '192.168.1.0/24'
      dhcpEnable: true
      gateway: 192.168.1.1
      name:
        concat:
          - 'subnet-'
          - {get_input: HuaweiCloud.StackName}
      primaryDns: 8.8.8.8
      secondaryDns: 114.114.114.114
      vpcId:
        get_reference: vpc-vpc
    requirements:
      - vpcId:
          node: vpc-vpc
    type: HuaweiCloud.VPC.Subnet
  vpc-vpc:
    metadata:
      Designer:
        id: 2617c555-7896-4b35-9427-bb10a72d7973
    properties:
      cidr: '192.168.0.0/16'
      name:
        concat:
          - 'vpc-'
          - {get_input: HuaweiCloud.StackName}
    type: HuaweiCloud.VPC.VPC
tosca_definitions_version: huaweicloud_tosca_version_1_0
outputs:
  master:
    description: master ips
    value:
      get_attribute:
        - ecs-master
        - publicIps
  gateway:
    description: gateway ips
    value:
      get_attribute:
        - ecs-gateway
        - publicIps
  storage:
    description: storage ips
    value:
      get_attribute:
        - ecs-storage
        - publicIps
  snat:
    description: snat ips
    value:
      get_attribute:
        - ecs-snat
        - publicIps
  node:
    description: node ips
    value:
      get_attribute:
        - ecs-node
        - publicIps
