---
- name: install packages
  when:
    - ansible_os_family == "RedHat"
  yum:
    state: present
    # update_cache: yes
    name:
      - bash-completion

- name: add bash-completion to ~/.bashrc for kubectl
  lineinfile:
    dest: "{{ lookup('env', 'HOME') }}/.bashrc"
    line: "source <(kubectl completion bash)"
    state: present

- name: add bash-completion to ~/.bashrc for kubectl
  lineinfile:
    dest: "{{ lookup('env', 'HOME') }}/.bashrc"
    line: "source <(kubeadm completion bash)"
    state: present
