---
- name: check if kubadm installed or not
  stat:
    path: "/etc/kubernetes/admin.conf"
  register: var_kubeadm_conf

# 重置: ansible-playbook -i inventory reset-site.yaml
- name: kubeadm init ...
  include_tasks: kubeadm_init.yml
  when:
    - (groups['master'] | length > 0)
    - not var_kubeadm_conf.stat.exists

- name: kubectl bash completion
  include_tasks: kubectl_completion.yml

- name: kubectl apply ...
  when:
    # 限定只在首节点运行
    - groups['master'][0] == inventory_hostname
  include_tasks: kubectl_apply.yml

- name: generate kubeadm join command ...
  when:
    # 限定只在首节点运行
    - groups['master'][0] == inventory_hostname
  include_tasks:
    file: kubeadm_join.yml
    apply:
      tags:
        - node
  tags:
    - always