---
- name: ensures kubernetes server dirs
  file: path={{ item }} state=directory
  with_items:
    - /etc/systemd/system
    - /etc/kuberentes/mainifest
    - /usr/local/bin
    - "{{ lookup('env', 'HOME') }}/k8s"
    - "{{ lookup('env', 'HOME') }}/.kube"

- name: check if kubadm installed or not
  stat:
    path: "/etc/kubernetes/admin.conf"
  register: var_kubeadm_conf
- debug: var=var_kubeadm_conf

# 重置: ansible-playbook -i inventory reset-site.yaml
- name: step 1 kubeadm init start ...
  when:
   - (groups['master'] | length > 0)
   - not var_kubeadm_conf.stat.exists
  include_tasks: 01-kubeadm_init.yaml

