---

- name: ensures kubernetes server dirs
  file: path={{ item }} state=directory
  with_items:
   - /etc/systemd/system
   - /etc/kuberentes/mainifest
   - /usr/local/bin

- name: handle kubernetes-server
  when: "'master' in group_names"
  unarchive: 
   src: "/tmp/repository/kubernetes-server_{{ kubernetes_version }}_linux_amd64.tar.gz"
   dest: '/usr/local/bin'
   remote_src: yes
   extra_opts: 
      - --strip=3
   exclude:
    - '*.tar'
    - '*.docker_tag'

