---

- name: 1.1 ensures docker dirs
  file: path={{ item }} state=directory
  with_items:
   - /etc/systemd/system
   - /etc/docker
   - /var/lib/docker

- name: 1.7 try restart docker daemon
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
    enabled: yes

- command: systemctl is-active docker