---

- name: ensures kubernetes server dirs
  file: path={{ item }} state=directory
  with_items:
   - /etc/systemd/system
   - /etc/kuberentes/mainifest
   - /usr/local/bin
   - /root/k8s

- name: handle kubernetes-server
  when: "'master' in group_names"
  unarchive: 
   src: "/tmp/repository/kubernetes-server_{{ kubernetes_version }}_linux_amd64.tar.gz"
   dest: '/usr/local/bin'
   remote_src: yes
   extra_opts: 
      - --strip=3
   exclude:
    - '*.tar'
    - '*.docker_tag'

- name: genrate kubeadmcfg
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
  - { src: "kubeadmcfg.yml.j2", dest: "/root/k8s/kubeadmcfg.yml" }

- name: kubeadm init
  when: groups['master'][0] == inventory_hostname
  shell: |
   cd /root/k8s
   kubeadm init --config=kubeadmcfg.yml
  register: kubeadm_init
- debut: var=kubeadm_init

